use crate::emulator::FRAME;
use crate::nes_memory::NesMemory;
use crate::rom::Rom;
use crate::get_bit;
use once_cell::sync::Lazy;
use std::sync::RwLock;
use std::time::Instant;
use tracing::{debug, error, info};
use crate::constants::*;
use crate::mappers::mapper_base::{MapperBase, VramType};
use crate::ppu_ctrl::PpuCtrl;

#[derive(Default)]
pub struct PpuResult {
    pub vbl: bool,
    pub frame_start: bool,
    pub frame_end: bool,
    pub irq_requested: bool,
}

pub const VRAM_SIZE: usize = 0x4000;

// 0x3f10 content at reset
const DEFAULT_SPRITE_PALETTE: [u8;16] = [
    0x09, 0x01, 0x34, 0x03, 0x00, 0x04, 0x00, 0x14, 0x08, 0x3A, 0x00, 0x02, 0x00, 0x20, 0x2C, 0x08
// 0x09,, 0x01, 0x00, 0x01, 0x00, 0x02, 0x02, 0x0D, 0x08, 0x10, 0x08, 0x24, 0x00, 0x00, 0x04, 0x2C
];

/// The PPU outputs a picture region of 256x240 pixels and a border region
/// extending 16 pixels left, 11 pixels right, and 2 pixels down (283x242).
/// The picture region is generated by doing memory fetches that fill shift registers,
/// from which a pixel is selected. It is composed of a background region
/// filling the entire screen and smaller sprites that ...
/// the PPU renders 262 scan lines per frame
/// each scanline lasts for 341 PPU clock cycles
/// const int NES_CYCLES_PER_FRAME = 29822; // 60 FPS
pub struct Ppu {
    // 0..261
    pub scanline: u16,
    // 0..340
    pub cycle: u16,
    pub rom: Rom,
    pub palette_table: [u8; 32],
    pub(crate) oam: [u8; 256],
    pub ppu_ctrl: PpuCtrl,
    sprite_0_hit: bool,
    screen: [u8; WIDTH * HEIGHT],
    background_pixel_indices: [u8; WIDTH * HEIGHT],
    last_screen_sent: Instant,
    pub oam_address: u8,
    open_bus: u8,
    // When was last time open_bus was written, used to simulate decay
    open_bus_last_cycle_written: u32,
    // Incremented for every tick, used to calculate when the CPU ticks once
    // (ppu_cycle % 3 == 0)
    ppu_cycle: u64,
    // Keep track of even/odd so we can skip a dot every other frame
    // https://www.nesdev.org/wiki/PPU_frame_timing
    odd_frame: bool,
}

impl Default for Ppu {
    fn default() -> Self {
        Self {
            scanline: 0,
            cycle: 25,
            rom: Rom::default(),
            palette_table: [0; 32],
            oam: [0; 256],
            ppu_ctrl: PpuCtrl::default(),
            sprite_0_hit: false,
            screen: [0; WIDTH * HEIGHT],
            background_pixel_indices: [0; WIDTH * HEIGHT],
            last_screen_sent: Instant::now(),
            oam_address: 0,
            open_bus: 0,
            open_bus_last_cycle_written: 0,
            ppu_cycle: 0,
            odd_frame: false,
        }
    }
}

pub const CYCLES : u16 = 341;
pub const SCANLINES: u16 = 262;

pub static CURRENT_CYCLE: Lazy<RwLock<u16>> = Lazy::new(|| RwLock::new(0));
pub static CURRENT_SCANLINE: Lazy<RwLock<u16>> = Lazy::new(|| RwLock::new(0));

impl Ppu {
    pub fn set_open_bus(&mut self, value: u8) {
        self.open_bus_last_cycle_written = 0;
        self.open_bus = value;
    }

    pub fn get_open_bus(&self) -> u8 {
        if self.open_bus_last_cycle_written > 5_369_318 {
            // info!("#Open bus decayed to 0");
            0
        } else {
            // info!("#Returning open bus: {:02X}", self.open_bus);
            if self.open_bus == 2 { 0x18 } else {
                self.open_bus
            }
        }
    }

    pub fn new_for_testing(mapper: &mut MapperBase) -> Self {
        let mut result = Self::default();
        for i in 0..VRAM_SIZE {
            result.set_vram(i, 0, mapper);
        }
        result
    }

    pub(crate) fn new(mapper: &mut MapperBase) -> Self {
        let mut result = Self {
            ..Default::default()
        };
        for i in 0..DEFAULT_SPRITE_PALETTE.len() {
            result.set_vram(0x3f10 + i, DEFAULT_SPRITE_PALETTE[i], mapper);
        }
        result
    }

    pub fn get_vram(&self, address: usize, mapper: &mut MapperBase) -> u8 {
        let after = NesMemory::ppu_mirrorring(address as u16) as usize;
        let result = if (0x2000..=0x2fff).contains(&after) {
            mapper.read_nametable(after)
        } else if address >= 0x3f00 {
            self.palette_table[after & 0x1f]
        } else {
            mapper.read_chr(after as u16)
        };
        result
    }

    pub fn set_vram(&mut self, address: usize, value: u8, mapper: &mut MapperBase) {
        let after = NesMemory::ppu_mirrorring(address as u16) as usize;
        if (0x2000..=0x2fff).contains(&after) {
            mapper.write_nametable(after, value);
        } else if address >= 0x3f00 {
            self.palette_table[after & 0x1f] = value & 0x3f;
        } else {
            mapper.write_chr(after as u16, value);
        };
    }

    /// Return 0, 1, 2, or 3
    /// If 0, that color is transparent
    fn get_color_index(&self, tile_index: usize, x: u16, y: u16, is_first_table: bool,
            mapper: &mut MapperBase) -> u8 {
        let bytes_offset = if is_first_table { 0 } else { 0x1000 } + tile_index * 16;
        let y_in_tile = (y as usize) % 8;
        let plane0_byte = self.get_vram(bytes_offset + y_in_tile, mapper);      // Low bit plane
        let plane1_byte = self.get_vram(bytes_offset + y_in_tile + 8, mapper);  // High bit plane

        // Get the specific pixel bits (pixels are rendered left to right)
        let bit_shift = 7 - (x % 8);
        let bit0 = (plane0_byte >> bit_shift) & 1;  // Low bit
        let bit1 = (plane1_byte >> bit_shift) & 1;  // High bit

        // Combine to get 2-bit color index (0-3)
        (bit1 << 1) | bit0
    }

    /// Return (color_index, result_color, sprite_0_hit)
    fn background_color(&self, sprite_rendering: bool, background_rendering: bool,
        memory: &mut NesMemory) -> (u8, u8, bool)
    {
        let x = self.cycle;
        let mut result_hit = self.sprite_0_hit;

        if !background_rendering && !sprite_rendering {
            let color = if memory.ir.v >= 0x3f00 && memory.ir.v <= 0x3fff {
                self.get_vram(memory.ir.v as usize, &mut memory.mapper)
            } else {
                self.get_vram(0x3f00, &mut memory.mapper)
            };
            return (0, color, result_hit);
        }

        if x < 8 && memory.ppu_mask.clip_background {
            return (0, self.get_vram(0x3f00, &mut memory.mapper), result_hit);
        }

        if !background_rendering {
            return (0, self.get_vram(0x3f00, &mut memory.mapper), result_hit);
        }

        let y = self.scanline;

        // Apply fine X scroll by potentially sampling from the next tile and the
        // proper in-tile pixel based on IR.x (fine X)
        let fine_x = memory.ir.fine_x();
        let x_in_tile_base = x % 8;
        let x_eff = x_in_tile_base + fine_x; // 0..15
        let use_next_tile = x_eff >= 8;
        let in_tile_x = x_eff % 8; // pixel within the selected tile (0..7)

        // Select the effective tile by adding one tile to the right when needed,
        // including nametable wrap when coarse X is 31
        let v_current = memory.ir.v;
        let v_effective = if use_next_tile {
            if (v_current & 0x1F) == 31 {
                // Wrap coarse X to 0 and toggle horizontal nametable
                (v_current & !0x1F) ^ 0x0400
            } else {
                v_current + 1
            }
        } else {
            v_current
        } & 0x0FFF; // keep within nametable addressing bits

        let tilemap_address = 0x2000 | v_effective as usize;
        let tile_index = self.get_vram(tilemap_address, &mut memory.mapper) as usize;
        let is_first_table = memory.ppu_ctrl.background_table == 0;
        let color_index = self.get_color_index(tile_index, in_tile_x,
            memory.ir.fine_y(), is_first_table, &mut memory.mapper);

        // if /* *BREAKPOINT.read().unwrap() && */ x == 96 && y == 64 {
        //     info!("tilemap_address:{tilemap_address:04X} \
        //     tile_index:{tile_index:02X} \
        //     color_index:{color_index:02X} \
        //     x:{} \
        //     ir:{}", memory.ir.x, memory.ir);
        //     println!();
        // }
        let palette_address = if color_index == 0 {
            0
        } else {
            // Use the effective v (potentially pointing to the next tile)
            let v = v_effective;
            // Attribute byte covers 4x4 tiles (32x32 pixels)
            let attribute_address = 0x23c0
                | v & 0x0c00
                | (v >> 4) & 0x38
                | (v >> 2) & 7;
            let attribute_data = self.get_vram(attribute_address as usize, &mut memory.mapper);

            // Determine which 2x2 tile quadrant we're in
            let tile_x = (v & 0x1F) as u16; // coarse X from effective v
            let tile_y = ((v >> 5) & 0x1F) as u16; // coarse Y from effective v
            let quadrant_x = (tile_x % 4) / 2;  // 0 or 1
            let quadrant_y = (tile_y % 4) / 2;  // 0 or 1
            let quadrant = (quadrant_y * 2) + quadrant_x;

            // Extract 2-bit palette number from attribute byte
            let palette_index = (attribute_data >> (quadrant * 2)) & 0x03;
            // Calculate final palette address
            palette_index as usize * 4 + color_index as usize

            // if *BREAKPOINT.read().unwrap() && x == 121 && y == 112 {
            //     println!("Tile info for {},{} \
            //     tilemap_address:{tilemap_address:04X} \
            //     tile_index:{tile_index:02X} \
            //     palette_index:{palette_index:02X} \
            //     palette_address:{palette_address:04X} \
            //     attribute_address:{attribute_address:04X} \
            //     attribute_data:{attribute_data:02X} \
            //     color_index:{color_index:02X} \
            //     ",
            //         x, y);
            //     println!("BREAKPOINT, ir:{}", memory.ir);
            //     println!();
            //
            // }
        };
        let result_color = self.get_vram(0x3f00 + palette_address, &mut memory.mapper);

        //
        // Sprite 0 detection
        //
        if self.sprite_0_hit {
            // Already set
        } else if x < 8 && (memory.ppu_mask.clip_background || memory.ppu_mask.clip_sprites) {
            // No hit when clipping
        } else if y > 0 {
            let is_sprite_transparent = self.sprite_color_at_coordinates(0, x, y, &mut memory.mapper)
                .is_none();
            let is_background_transparent = color_index == 0;
            result_hit |= sprite_rendering && background_rendering
                    && !is_background_transparent && !is_sprite_transparent
                    && x < 255;

            // if *BREAKPOINT.read().unwrap() {
            //     info!("{x},{y} hit:{} \
            //     background_transparent:{is_background_transparent} \
            //     sprite_transparent:{is_sprite_transparent}", self.sprite_0_hit);
            // }
            // if *BREAKPOINT.read().unwrap() && x == 128 && y == 120 {
            //     println!("sprite_color:{sprite_color_index} \
            //     sprite_transparent:{is_sprite_transparent} \
            //     background_transparent:{is_background_transparent} x:{x} y:{y} \
            //     sprite_0_x:{sprite_0_x} sprite_0_y:{sprite_0_y} \
            //     sprite_height:{sprite_height} \
            //     sprite_tile_index:{sprite_tile_index} \
            //     color_index:{color_index} \
            //     tile_index:{tile_index}");
            //     println!("BUG HERE");
            // }
        }

        (color_index, result_color, result_hit)
    }

    /// Return true if sprite overflow
    fn draw_sprites_on_scanline(&mut self, y: u16, memory: &mut NesMemory) -> bool {
        let mut sprites_on_scanline = Vec::new();
        let sprite_height = self.ppu_ctrl.sprite_height as u16;

        for i in 0..64 {
            let sprite_y = 1 + self.oam[i * 4] as u16;
            if y >= sprite_y && y < sprite_y + sprite_height {
                if sprites_on_scanline.len() < 8 {
                    sprites_on_scanline.push(i);
                } else {
                    return true;
                }
            }
        }

        for x in 0..WIDTH {
            if x < 8 && memory.ppu_mask.clip_sprites {
                continue;
            }
            for &sprite_index in &sprites_on_scanline {
                if let Some((sprite_color, behind_bg)) =
                        self.sprite_color_at_coordinates(sprite_index, x as u16, y, &mut memory.mapper) {
                    let index = y as usize * WIDTH + x;
                    let bg_index = self.background_pixel_indices[index];

                    if !behind_bg || bg_index == 0 {
                        self.screen[index] = sprite_color;
                    }
                    // First non-transparent sprite at this x wins
                    break;
                }
            }
        }
        false
    }

    pub fn update_internal_registers(&mut self, memory: &mut NesMemory) {
        let x = self.cycle;
        let y = self.scanline;

        // Increment coarse X
        if x < 256 && x != 0 && (x % 8) == 0 {
            if memory.ir.coarse_x() == 31 {
                memory.ir.set_coarse_x(0);
                memory.ir.switch_horizontal_nametable();
                // let old = memory.ir.clone();
                debug!(target: "ir", "Flipping horizontal nametable, new:{}", memory.ir);
                // println!("{x},{y} Flipping horizontal nametable, old:{} new:{}",
                //     old.nametable(), memory.ir.nametable());
                // println!();
            } else {
                memory.ir.increment_coarse_x();
            }
        }

        // Increment coarse Y at dot 256
        if x == 256 {
            if memory.ir.fine_y() < 7 {
                memory.ir.increment_fine_y();
            } else {
                memory.ir.set_fine_y(0);
                let mut coarse_y = memory.ir.coarse_y();
                // if coarse_y == 31 {
                //     println!("BP COARSE_Y");
                // }
                if coarse_y == 29 {
                    coarse_y = 0;
                    // let old = memory.ir.clone();
                    memory.ir.switch_vertical_nametable();
                    debug!(target: "ir", "Flipping vertical nametable, new:{}", memory.ir);
                    // println!();
                } else if coarse_y == 31 {
                    coarse_y = 0; // coarse Y = 0, nametable not switched
                } else {
                    coarse_y += 1; // increment coarse Y
                }
                memory.ir.set_coarse_y(coarse_y);
            }
        }

        if x == 257 {
            memory.ir.hori_v_equals_hori_t();
        }

        if y == 261 && x >= 280 && x <= 304 {
            memory.ir.vert_v_equals_vert_t();
        }
    }

    pub fn update_memory(&mut self, sprite_overflow: bool, memory: &mut NesMemory) -> PpuResult {
        let mut result = PpuResult::default();
        let x = self.cycle;
        let y = self.scanline;
        if sprite_overflow {
            memory.set_bit(0x2002, BIT_SPRITE_OVERFLOW);
        }
        if y <= 239 {
            if y == 0 && x == 0 {
                result.frame_start = true;
                memory.clear_bit(0x2002, BIT_SPRITE_OVERFLOW);
            } else if x < 256 {
                // Sprite 0 hit
                if self.sprite_0_hit {
                    debug!(target:"vbl", "SPRITE_0:on");
                    memory.set_bit(0x2002, BIT_SPRITE_0_HIT);
                }
            } else {
                // 256..321,  HBLANK
                self.oam_address = 0;
            }
        } else if y == 240 {
            if x == 333 {
                // VBL on
                debug!(target: "vbl", "VBL:on");
                memory.set_bit(0x2002, BIT_VBL);
                // let v = memory.get(0x2002) | 0b1000_000;
                // memory.set(0x2002, v);
                result.vbl = true;
                if self.last_screen_sent.elapsed().as_millis() > 16 {
                    unsafe {
                        FRAME = <[u8; 61440]>::try_from(self.screen.clone()).unwrap();
                        self.last_screen_sent = Instant::now();
                    }
                }
            }
            if x == 0 {
                result.frame_end = true;
            }
        } else if y <= 261 {
            if x == 1 && y == 261 {
                // Clear VBL
                debug!(target: "vbl", "VBL:off SPRITE_0:off");
                memory.clear_bit(0x2002, BIT_VBL);
                // Clear sprite 0 hit
                memory.clear_bit(0x2002, BIT_SPRITE_0_HIT);
            }
        }

        result
    }

    /// Draw the background
    fn draw_background(&mut self, memory: &mut NesMemory, index: usize, sprite_rendering: bool,
            background_rendering: bool)
    {
        let (color_index, background_color, hit) =
            self.background_color(sprite_rendering, background_rendering, memory);
        if background_color >= 64 {
            error!("Invalid background color: {background_color}");
            panic!();
        }
        self.screen[index] = background_color;
        self.background_pixel_indices[index] = color_index;
        self.sprite_0_hit |= hit;
    }

    /// Return true if VBL
    pub fn tick(&mut self, sprite_rendering: bool, background_rendering: bool,
        memory: &mut NesMemory) -> PpuResult
    {
        let x = self.cycle;
        let y = self.scanline;
        let index = y as usize * WIDTH + x as usize;
        let mut sprite_overflow = false;
        let mut irq_requested = false;
        self.open_bus_last_cycle_written += 1;

        *CURRENT_CYCLE.write().unwrap() = self.cycle;
        *CURRENT_SCANLINE.write().unwrap() = self.scanline;

        // info!("PPU TICK: {}", CURRENT_CYCLE.read().unwrap());

        // Notify the mapper for each CPU cycle
        if (self.ppu_cycle % 3) == 0 {
            irq_requested = memory.mapper.on_cpu_cycle();
        }

        if y < 240 {
            if x < 256 {
                self.draw_background(memory, index, sprite_rendering, background_rendering);
            }
            if x == 256 {
                if sprite_rendering || background_rendering {
                    sprite_overflow = self.draw_sprites_on_scanline(y, memory);
                }
            }
            // TODO: this should be more nuanced: https://www.nesdev.org/wiki/MMC3
            // When using 8x8 sprites, if the BG uses $0000, and the sprites use $1000, the IRQ
            // counter should decrement on PPU cycle 260, right after the visible part of the
            // target scanline has ended.
            // When using 8x8 sprites, if the BG uses $1000, and the sprites use $0000, the IRQ
            // counter should decrement on PPU cycle 324 of the previous scanline (as in, right
            // before the target scanline is about to be drawn). However, the 2C02's pre-render
            // scanline will decrement the counter twice every other vertical redraw, so the IRQ
            // will shake one scanline. This is visible in Wario's Woods: with some PPU-CPU reset
            // alignments the bottom line of the green grass of the play area may flicker black
            // on the rightmost ~48 pixels, due to an extra count firing the IRQ one line
            // earlier than expected.
            if x == 260 {
                irq_requested = memory.mapper.on_scanline();
            }
        }

        let mut result = self.update_memory(sprite_overflow, memory);
        result.irq_requested = irq_requested;
        let rendering_enabled =
            memory.ppu_mask.background_rendering() || memory.ppu_mask.sprite_rendering();
        self.update_beam(rendering_enabled);

        if (background_rendering || sprite_rendering) && (y < 240 || y == 261) {
            self.update_internal_registers(memory);
        }

        result
    }

    pub fn update_beam(&mut self, rendering_enabled: bool) {
        // Increment cycle/scanline
        self.cycle += 1;
        let max = CYCLES;
        if self.cycle == CYCLES - 1 {
            self.odd_frame = ! self.odd_frame;
            self.cycle = 0;
            self.scanline += 1;
            if self.scanline == SCANLINES {
                self.scanline = 0;
                self.sprite_0_hit = false;
                // Skip dot 0 on odd frames
                if ! self.odd_frame && rendering_enabled { self.cycle = 1 };
            }
        }
    }
    fn calculate_palette_index_tile_offset(&self, x: u16, y: u16, tile_offset: usize,
        mapper: &mut MapperBase) -> usize
    {
        // Get the bytes for this row
        let y_in_tile = y % 8;
        let byte1 = self.get_vram(tile_offset + y_in_tile as usize, mapper);
        let byte2 = self.get_vram(tile_offset + y_in_tile as usize + 8, mapper);

        // Extract the bit at position (7 - (x % 8)) from each byte
        let bit_position = 7 - (x % 8);
        let bit1 = get_bit!(byte1, bit_position);
        let bit2 = get_bit!(byte2, bit_position);

        // Combine the bits to form the palette index
        ((bit2 << 1) | bit1) as usize
    }

    /// Return Some(sprite_color, behind_bg) or None if the sprite is missed or transparent
    /// x and y are screen coordinates
    fn sprite_color_at_coordinates(&self, sprite_index: usize, x: u16, y: u16,
        mapper: &mut MapperBase)
    -> Option<(u8, bool)> {
        let i = sprite_index * 4;
        let sprite_x = self.oam[i + 3] as u16;
        let sprite_y = 1 + self.oam[i + 0] as u16;
        let sprite_height = self.ppu_ctrl.sprite_height as u16;
        if ! (sprite_x <= x && x < sprite_x + 8 && sprite_y <= y && y < sprite_y + sprite_height) {
            return None;
        }

        let temp_tile_index = self.oam[i + 1] as u16;

        let mut y_in_tile = y - sprite_y;
        let mut x_in_tile = x - sprite_x;

        let sprite_attr = self.oam[i + 2];
        let vertical_flip = sprite_attr & 0x80 != 0;

        let tile_index = if sprite_height == 16 {
            let t = temp_tile_index & 0xfe;
            // If vertical flipping, both the tiles are swapped *and* they also get flipped
            // vertically by pixel.
            if y_in_tile < 8 {
                if vertical_flip { t + 1 } else { t }
            } else {
                y_in_tile -= 8;
                if vertical_flip { t } else { t + 1}
            }
        } else {
            temp_tile_index
        };

        // Calculate palette data
        let behind_bg = (sprite_attr & 0x20) != 0;

        // Handle flipping at the pixel level
        if vertical_flip { y_in_tile = 7 - y_in_tile };
        if sprite_attr & 0x40 != 0 { x_in_tile = 7 - x_in_tile };

        let is_first_table = if sprite_height == 8 {
            self.ppu_ctrl.sprite_table == 0
        } else {
            // For 8x16 sprites, bit 0 of the tile index determines the pattern table
            (temp_tile_index & 1) == 0
        };
        let tile_offset = if is_first_table { 0 } else { 0x1000 } + tile_index * 16;
        let palette_index = self.calculate_palette_index_tile_offset(
            // &self.rom.chr_rom,
            x_in_tile, y_in_tile,
            tile_offset as usize,
            mapper,
        );

        // Skip transparent pixels
        if palette_index == 0 {
            return None;
        }

        // Calculate final color
        let palette_number = sprite_attr & 0x3;
        let system_index = self.get_vram(0x3f10 + palette_number as usize * 4 + palette_index, mapper);

        // if x == 56 && y == 128 {
        //     println!("tile_index:{tile_index:02X} \
        //     palette_index:{palette_index:02X} \
        //     tile_offset:{tile_offset:04X} \
        //     [6f0]:{:02X}  \
        //     ", self.get_vram(0x6f0));
        //     info!("Displaying sprite");
        // }

        // Return the color and whether it's behind the background
        Some((system_index, behind_bg))
    }

    pub fn write_oam(&mut self, address: u8, value: u8) {
        debug!(target: "oam", "write_oam({address:04X}={value:02X})");
        self.oam[address as usize] = value;
    }

    // pub fn set_sprite_0_hit(&mut self, value: bool) {
    //     let mut ctrl = self.get_vram(0x2002];
    //     if value { ctrl |= 0b0100_0000 } else { ctrl &= 0b1011_1111 }
    //     self.get_vram(0x2002] = ctrl;
    // }
}

pub const BIT_SPRITE_OVERFLOW: u8 = 5;
pub const BIT_SPRITE_0_HIT: u8 = 6;
pub const BIT_VBL: u8 = 7;